server:
  port: 8083

spring:
  application:
    name: matching-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers

logging:
  level:
    com.caringiggy: DEBUG
